apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapps
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
          owner: manisbindra
          repo: ephemeral-app
      requeueAfterSeconds: 120
  template:
    metadata:
      name: 'app-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/maniSbindra/ephemeral-env-infra.git'
        # targetRevision: '{{head_sha}}'
        path: ephemeral-env
        helm:
          parameters:
          - name: "prSHA"
            value: "{{head_sha}}"
          - name: "prNumber"
            value: "{{number}}"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'appset-ephem-ns'
      syncPolicy:
          automated:
              allowEmpty: true
              prune: true
              selfHeal: true
